# Generated by Django 4.2.29 on 2026-03-14 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conciliacao", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagamento",
            name="bandeira",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="pagamento",
            name="cartao_final",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
